name: Tag release

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  tag-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    name: Tag release
    steps:
      - name: Compute next SemVer
        id: update_semver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.MASTER_PUSH_TOKEN }}
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2.1
      - name: Update version in pyproject.toml
        run: |
          V_VERSION=${{ steps.update_semver.outputs.tag }}
          poetry version "${V_VERSION//v/}"
      - name: Update Helm Chart.yaml
        uses: mikefarah/yq@v4.27.5
        with:
          cmd: yq '.appVersion = "${{ steps.update_semver.outputs.tag }}"' -i helm/fritz-exporter/Chart.yaml
      - name: Commit pyproject.toml and Chart.yaml back to repo
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add pyproject.toml helm/fritz-exporter/Chart.yaml
          git commit -m "Update pyproject.toml for version ${{ steps.update_semver.outputs.tag }}"
      - name: Push version updates back to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MASTER_PUSH_TOKEN }}
          branch: ${{ github.ref }}
      - name: Push SemVer release tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.MASTER_PUSH_TOKEN }}
